// The e2e tests never touch the real songs. They play and edit one throwaway
// song, src/songs/zz-e2e-fixture.ts, which this module writes. The songs glob
// (src/songs/index.ts: "./*.ts") picks it up like any other song.
//
// The test server doesn't serve the checkout itself but a snapshot of the app
// (index.html + src/) in .e2e-app/, made by e2e/serve.ts on startup, and the
// fixture lives in that snapshot. A `npm run dev` player running from the
// checkout at the same time therefore never sees the fixture: with "follow
// edits" on it would otherwise jump to it on every test edit, and the VS Code
// extension would show the tests' deliberate errors. It also keeps the
// fixture away from tsc/check-songs.
//
// Lifecycle: serve.ts recreates .e2e-app/ (fixture included) before Vite
// starts, tests rewrite the fixture, and .e2e-app/ is deleted when the server
// exits (and git-ignored in case a run is killed).
//
// No dependencies on Playwright: serve.ts runs this under plain Node.

import { cpSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

/** The checkout */
export const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
/** The snapshot the e2e Vite server serves (its root) */
export const APP_ROOT = resolve(ROOT, ".e2e-app");
export const FIXTURE_ID = "zz-e2e-fixture";
/** Vite-root-relative path, as the bridge reports it */
export const FIXTURE_FILE = `src/songs/${FIXTURE_ID}.ts`;
/** What PlayerState.error.file holds (basename) */
export const FIXTURE_BASENAME = `${FIXTURE_ID}.ts`;
export const FIXTURE_PATH = resolve(APP_ROOT, FIXTURE_FILE);

/** Files and directories of the checkout that make up the served app */
const APP_FILES = ["index.html", "src"];

/** (Re)create the app snapshot in APP_ROOT, with the default fixture. */
export function createAppSnapshot() {
  removeAppSnapshot();
  mkdirSync(APP_ROOT, { recursive: true });
  for (const entry of APP_FILES) cpSync(resolve(ROOT, entry), resolve(APP_ROOT, entry), { recursive: true });
  writeFixture();
}

export function removeAppSnapshot() {
  rmSync(APP_ROOT, { recursive: true, force: true });
}

/** Synth used by the fixture's only track; probes look up haps by this `s` value. */
export const FIXTURE_SOUND = "triangle";

/** Window flag that makes a `queryErrorWhenFlagged` fixture throw at query time */
export const BOOM_FLAG = "__e2eBoom";

/** The fixture knob's name when FixtureOptions.gainKnob is set */
export const KNOB_NAME = "level";

export const BUILD_ERROR_MESSAGE = "e2e: createPattern failed on purpose";
export const QUERY_ERROR_MESSAGE = "e2e: query failed on purpose";

export interface FixtureOptions {
  name?: string;
  bpm?: number;
  gain?: number;
  /** Use `knob(KNOB_NAME, gainKnob, 0, 1)` as the gain instead of a number (see knobs.spec.ts) */
  gainKnob?: number;
  sound?: string;
  /** createPattern() throws (on its own line, see lineOf(BUILD_ERROR_MESSAGE)) */
  buildError?: boolean;
  /** The pattern throws when queried while window[BOOM_FLAG] is truthy */
  queryErrorWhenFlagged?: boolean;
  /** Two 2-bar sections, FIXTURE_SECTIONS (for jump/loop tests) */
  sections?: boolean;
  /**
   * A second track, PULSE_TRACK: one token retriggered four times a cycle
   * (PULSE_TOKEN, like "bd*4") on its own synth, PULSE_SOUND
   */
  pulse?: boolean;
}

export const FIXTURE_SECTIONS = [
  ["a", 2],
  ["b", 2],
] as const;
export const PULSE_TRACK = "pulse";
export const PULSE_TOKEN = "c4*4";
export const PULSE_SOUND = "sine";

export const DEFAULT_FIXTURE = {
  name: "E2E Fixture",
  bpm: 120,
  gain: 0.5,
  sound: FIXTURE_SOUND,
} as const;

export function fixtureSource(options: FixtureOptions = {}): string {
  const { name, bpm, gain, sound } = { ...DEFAULT_FIXTURE, ...options };
  const gainExpr = options.gainKnob === undefined ? String(gain) : `knob(${JSON.stringify(KNOB_NAME)}, ${options.gainKnob}, 0, 1)`;
  const queryError = options.queryErrorWhenFlagged
    ? `\n      .withValue((v) => {\n        if (globalThis.${BOOM_FLAG}) throw new Error(${JSON.stringify(QUERY_ERROR_MESSAGE)});\n        return v;\n      })`
    : "";
  const sections = options.sections ? `\n  sections: ${JSON.stringify(FIXTURE_SECTIONS)},` : "";
  const pulse = options.pulse
    ? `\n    const ${PULSE_TRACK} = note(${JSON.stringify(PULSE_TOKEN)}).s(${JSON.stringify(PULSE_SOUND)}).gain(${gain});`
    : "";
  return `// @ts-nocheck
// Generated by e2e/fixture.ts for the end-to-end tests. Deleted after the run.
import type { Song } from ".";

const song: Song = {
  name: ${JSON.stringify(name)},
  bpm: ${bpm},
  visualization: "none",${sections}
  createPattern() {
    // padding line
    ${options.buildError ? `throw new Error(${JSON.stringify(BUILD_ERROR_MESSAGE)});` : "// no error"}
    const lead = note("c3 e3 g3 b3")
      .s(${JSON.stringify(sound)})
      .gain(${gainExpr})${queryError};${pulse}
    return { lead${options.pulse ? `, ${PULSE_TRACK}` : ""} };
  },
};

export default song;
`;
}

/**
 * Minimum time between two writes of the fixture. Vite's file watcher
 * (chokidar 3, bundled with Vite 5) throttles `change` events per path: a
 * change within 50 ms of the previous one is dropped, not delayed, so Vite
 * never sends an HMR update for it and the page keeps the previous version
 * for good. The 50 ms start when the watcher emits the previous change, a
 * little after that write, hence the margin. Nobody saves a file twice that
 * fast by hand, but a test that writes, waits for a quick round trip (a
 * build error is reported without a swap) and writes again easily does.
 */
const MIN_WRITE_INTERVAL_MS = 100;

/** Block until the fixture's last write (by anyone: tests, serve.ts, knob write-back) is MIN_WRITE_INTERVAL_MS old. */
function waitForWatcher() {
  let mtimeMs: number;
  try {
    mtimeMs = statSync(FIXTURE_PATH).mtimeMs;
  } catch {
    return; // not there yet
  }
  const wait = Math.ceil(mtimeMs + MIN_WRITE_INTERVAL_MS - Date.now());
  // Synchronous on purpose: writeFixture() is sync at every call site.
  if (wait > 0) Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, wait);
}

/** Write the fixture and return its source. */
export function writeFixture(options: FixtureOptions = {}): string {
  const source = fixtureSource(options);
  // Skip identical writes: Vite would not emit an HMR update for them anyway,
  // and callers that wait for one should change something.
  let current: string | null = null;
  try {
    current = readFileSync(FIXTURE_PATH, "utf8");
  } catch {
    // not there yet
  }
  if (current !== source) {
    waitForWatcher();
    writeFileSync(FIXTURE_PATH, source);
  }
  return source;
}

/** 1-based line number of the first line containing `needle` */
export function lineOf(source: string, needle: string): number {
  const index = source.split("\n").findIndex((line) => line.includes(needle));
  if (index < 0) throw new Error(`"${needle}" not found in fixture source`);
  return index + 1;
}
